### ISSUE TITLE
how can try in my local instance

### ISSUE THREAD

**Issue by johnfelipe** [wp2opensim/openSIMULATOR-Map-Karte-PHP7#1]
Hi bro i have opensim 0.8.2.1 in gridcommon with robust pls tell me how can install in my php 7.1.4: http://200.122.209.133/phpinfo.php

Stay alert

**Comment by wp2opensim** [comment]
Make /includes writable
Run install.php and fill in the details, then click Install
Run map.php
Undo the make /includes directory
Delete Install.php
